[phases.setup]
aptPkgs = ["git"]

[variables]
NODE_ENV = "production"

[phases.build]
cmds = ["cd backend && npm install && npm run build"]

[start]
cmd = "cd backend && npm install && npm run prisma:migrate && npm start"
